default:
  tags:
    - origin:eclipse

smo:
  stage: build
  image: python:3.12

  variables:
    POSTGRESQL_DATABASE: smo
    POSTGRESQL_USER: root
    POSTGRESQL_PASSWORD: password

  services:
    - name: quay.io/sclorg/postgresql-15-c9s
      alias: postgres

  script:
    - export PGPASSWORD=$POSTGRESQL_PASSWORD
    - sleep 4
    - pip install .
    - make test
    - cd src
    - python app.py &> flask.log &
    - sleep 7
    - cat flask.log
