default:
  tags:
    - origin:eclipse

smo:
  stage: build
  image: python:3.12

  variables:
    POSTGRESQL_DATABASE: smo
    POSTGRESQL_USER: root
    POSTGRESQL_PASSWORD: password

  services:
    - name: quay.io/sclorg/postgresql-15-c9s
      alias: postgres

  script:
    - export PGPASSWORD=$POSTGRESQL_PASSWORD
    - export PATH=/usr/local/bin:$PATH
    - pip install uv
    - uv sync
    - uv run pytest
    # Smoke test for Flask app
    - cd src
    - uv run python app.py &> flask.log &
    - sleep 7
    - cat flask.log
