default:
  tags:
    - origin:eclipse

smo:
  stage: build
  image: python:3.12

  variables:
    POSTGRESQL_DATABASE: smo
    POSTGRESQL_USER: root
    POSTGRESQL_PASSWORD: password

  services:
    - name: quay.io/sclorg/postgresql-15-c9s
      alias: postgres

  before_script:
    - apt-get update -qq && apt-get install -y -qq npm

  script:
    - export PGPASSWORD=$POSTGRESQL_PASSWORD
    - export PATH=/builds/.local/bin:$PATH
    - pip install uv
    - uv sync
    - uv run pytest
    - uv run make lint
    # Smoke test for Flask app (still needs to be fixed)
    # - cd src
    # - uv run python app.py &> flask.log &
    # - sleep 7
    # - cat flask.log
