FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory in the container
WORKDIR /app

# Install uv (Rust-based fast Python package manager)
RUN pip install uv

COPY pyproject.toml uv.lock src README.md ./

# Install dependencies using uv
# This caches the dependency layer if these files don't change
RUN uv sync --no-cache # --no-cache can be useful in CI for fresh installs

#WORKDIR /app
#COPY pyproject.toml uv.lock /app/
#RUN --mount=type=cache,target=/root/.cache/uv \
#    uv sync --locked --no-install-project --no-dev
#COPY . /app
#RUN --mount=type=cache,target=/root/.cache/uv \
#    uv sync --frozen --no-dev


## Copy the rest of the application code
#COPY . .
#
## Expose the port your Flask app runs on (default Flask port is 5000)
#EXPOSE 5000
#
## Command to run your application
## Assuming your app.py is in the 'src' directory
#CMD ["python", "src/app.py"]
## If app.py is at the root of /app, then:
## CMD ["python", "app.py"]
