services:
  smo:
    restart: always
    container_name: smo
    build: .
    env_file:
    - config/flask.env
    volumes:
      - type: bind
        source: ~/.kube/
        target: /home/python/.kube
        read_only: true
      - type: bind
        source: ~/.docker/
        target: /home/python/.docker
        read_only: true
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    extra_hosts:
    - "host.docker.internal:host-gateway"

  postgres:
    restart: always
    container_name: postgres
    image: postgres:16.2
    environment:
      PGUSER: root
      POSTGRES_DB: smo_test
      POSTGRES_USER: smo_user
      POSTGRES_PASSWORD: smo_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 3s
