version = 1
SPDX-PackageName = "H3NI SMO"
SPDX-PackageSupplier = "Abilian SAS <contact@abilian.com>"
SPDX-PackageDownloadLocation = "https://github.com/abilian/nephele-smo-fork"

[[annotations]]
path = ["**/*.py", "**/Makefile"]
precedence = "aggregate"
SPDX-FileCopyrightText = """
2024-2025 Abilian SAS <contact@abilian.com>
2024-2025 National Technical University of Athens
"""
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."

[[annotations]]
path = ["**"]
precedence = "aggregate"
SPDX-FileCopyrightText = """
2024-2025 Abilian SAS <contact@abilian.com>
2024-2025 National Technical University of Athens
"""
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."

[[annotations]]
path = ["CODE_OF_CONDUCT.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Python Software Foundation"
SPDX-License-Identifier = "All rights reserved"

[[annotations]]
path = ["DCO.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Linux Foundation"
SPDX-License-Identifier = "All rights reserved"

[[annotations]]
path = ["docs/**", "notes/**", "*.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2025 Abilian SAS <contact@abilian.com>"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Directory may also includes code with other licenses and other copyright holders but those are clearly identified in the source code with prefixed comments. Only the not-explicitly licensed portions are licensed with information described here."
